/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsMeetcraftRouteImport } from './routes/projects.meetcraft'
import { Route as ProjectsKalavanshRouteImport } from './routes/projects.kalavansh'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsMeetcraftRoute = ProjectsMeetcraftRouteImport.update({
  id: '/meetcraft',
  path: '/meetcraft',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsKalavanshRoute = ProjectsKalavanshRouteImport.update({
  id: '/kalavansh',
  path: '/kalavansh',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/kalavansh': typeof ProjectsKalavanshRoute
  '/projects/meetcraft': typeof ProjectsMeetcraftRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/kalavansh': typeof ProjectsKalavanshRoute
  '/projects/meetcraft': typeof ProjectsMeetcraftRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/kalavansh': typeof ProjectsKalavanshRoute
  '/projects/meetcraft': typeof ProjectsMeetcraftRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/projects/kalavansh'
    | '/projects/meetcraft'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects/kalavansh' | '/projects/meetcraft' | '/projects'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/projects/kalavansh'
    | '/projects/meetcraft'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/meetcraft': {
      id: '/projects/meetcraft'
      path: '/meetcraft'
      fullPath: '/projects/meetcraft'
      preLoaderRoute: typeof ProjectsMeetcraftRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/kalavansh': {
      id: '/projects/kalavansh'
      path: '/kalavansh'
      fullPath: '/projects/kalavansh'
      preLoaderRoute: typeof ProjectsKalavanshRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsKalavanshRoute: typeof ProjectsKalavanshRoute
  ProjectsMeetcraftRoute: typeof ProjectsMeetcraftRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsKalavanshRoute: ProjectsKalavanshRoute,
  ProjectsMeetcraftRoute: ProjectsMeetcraftRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
